dota2: reboot

diff --git a/bin/dota2 b/bin/dota2
--- a/bin/dota2
+++ b/bin/dota2
@@ -1,29 +1,9 @@
 #!/bin/bash
 
-set -euo pipefail
+if [[ ! -e /dev/disk/by-uuid/7E2E6E1E2E6DCFA7 ]]; then
+    echo "disk not found"
+    notify-send "dota2" "disk not found"
+    exit 1
+fi
 
-_game_id="570"
-_game_window="Dota"
-
-:main() {
-    :steam steam://rungameid/$_game_id
-}
-
-:steam() {
-    if pgrep steam &>/dev/null; then
-        :exec steam "$@"
-    else
-        :exec steam-ext4 "$@"
-    fi
-}
-
-:exec() {
-    :log "\$ ${@}"
-    "${@}"
-}
-
-:log() {
-    echo "$(highlight fg red bold)$*$(highlight reset)"
-}
-
-:main "${@}"
+/bin/reboot
