expect, fuck you

diff --git a/bin/ssh-multi b/bin/ssh-multi
--- a/bin/ssh-multi
+++ b/bin/ssh-multi
@@ -6,7 +6,7 @@ set -euo pipefail
     local login
     local quiet
     local ask_pass
-    local ssh_args
+    local ssh_args=()
     local remote_command=()
     local servers=()
 
@@ -16,11 +16,16 @@ set -euo pipefail
         exit 1
     fi
 
+    if ! which sshpass >/dev/null 2>&1; then
+        echo "sshpass is not found."
+        exit 1
+    fi
+
     local password=$(:read-password $ask_pass)
-    local ssh_cmd_line=$(:get-ssh-cmdline "$ssh_args" "$login")
+    local ssh_cmd_line=$(:get-ssh-cmdline "${ssh_args[@]}" "$login")
 
     if $ask_pass; then
-        ssh_cmd_line+=' -oControlPath=none'
+        ssh_cmd_line+=' -oPubkeyAuthentication=no'
     fi
 
     local joined_command=$(paste -sd' ' <<< ${remote_command[@]})
@@ -42,7 +47,7 @@ set -euo pipefail
     eval $login_var=$(whoami)
     eval $ask_pass_var="false"
     eval $quiet_var="false"
-    eval $ssh_args_var="-oStrictHostKeyChecking=no"
+    eval $ssh_args_var=\(-oStrictHostKeyChecking=no -oCheckHostIP=no\)
 
     eval set -- "$(getopt -o AS:l:hq -- "${@}")"
 
@@ -63,15 +68,17 @@ set -euo pipefail
                 eval $quiet_var="true"
                 shift
                 ;;
-            -h)
-                :usage
-                exit 1
-                ;;
-            *)
+            -)
                 ;&
             --)
                 shift
                 break
+                ;;
+            *)
+                ;&
+            -h)
+                :usage
+                exit 1
                 ;;
         esac
 
@@ -143,11 +150,19 @@ set -euo pipefail
     local quiet=$4
     local remote_command=$5
 
-    if [ "$password" ]; then
+    if [ "$password" ] && \
+        ! :ssh-is-shared-connection $ssh_cmd_line "$server"
+    then
         :ssh-pass "${@}"
     else
         $ssh_cmd_line "$server" "$remote_command"
     fi
+}
+
+:ssh-is-shared-connection() {
+    shift
+
+    ssh -O check "${@}" # > /dev/null 2>&1
 }
 
 
@@ -159,33 +174,13 @@ set -euo pipefail
 
     shift 4
 
-    local send_error='send_error "\[connection failed\]\n$expect_out(buffer)"'
-    if $quiet; then
-        send_error='send_error "$expect_out(buffer)"'
-    fi
-
-    expect -f <(cat <<EXPECT
-        spawn -noecho $ssh_cmd_line $server {*}\$argv
-
-        log_user 0
-        expect {
-            assword: {
-                send "$password\r"
-            } eof {
-                $send_error
-                exit 1
-            }
-        }
-
-        interact
-EXPECT
-    ) "${@}" | tail -n+2  # expect still leaves empty line in place of password
+    sshpass -f <(printf "%s\n" "$password") $ssh_cmd_line "$server" "${@}"
 }
 
 
 :usage() {
     cat <<HELP
-Usage: ssh-multi [-A] [-S <ssh-args>] [-l <login>] <server>... - <cmd>...
+Usage: ssh-multi [-A] [-S <ssh-args>] [-l <login>] -- <server>... -- <cmd>...
 
 Options:
     -A             Ask password once and use it for all servers.
