vim-bundle: no more vim plug shit

diff --git a/bin/vim-bundle-restore b/bin/vim-bundle-restore
--- a/bin/vim-bundle-restore
+++ b/bin/vim-bundle-restore
@@ -1,3 +1,30 @@
 #!/bin/bash
 
-exec vim -S ~/.vim/bundle/versions.vim +PlugUpdate!
+tasks=()
+while read plugin commit; do
+    {
+        cd ~/.vim/bundle/$plugin/
+
+        _head=$(git rev-parse --short HEAD)
+        if [[ "$_head" != "$commit" ]]; then
+            _update=$(git remote update 2>&1)
+            if [[ $? -ne 0 ]]; then
+                echo "$plugin: error"
+                sed "s/^/$plugin: /" <<< "$_update" >&2
+                exit 1
+            fi
+
+            _checkout=$(git checkout "$commit" 2>&1)
+            if [[ $? -ne 0 ]]; then
+                echo "$plugin: error"
+                sed "s/^/$plugin: /" <<< "$_checkout" >&2
+                exit 1
+            fi
+        fi
+
+        echo "$plugin: success"
+    } &
+    tasks+=($!)
+done < ~/.vim/bundle/versions.vim
+
+wait ${tasks[@]}
